apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-rabbitmqcluster
spec:
  image: vslharbor.jura.ch/dockerhub/library/rabbitmq:3.9.13-management
  persistence:
    storage: 50Mi
    storageClassName: rabbitmq-ops
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1
      memory: 500Mi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1700
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  service:
    type: LoadBalancer