kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rabbitmq-ops
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.28.2.20
  share: /nfs/sandbox
reclaimPolicy: Delete
mountOptions:
  - hard
  - nfsvers=4.1
volumeBindingMode: Immediate